apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cyrus-lyrics-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: cyrus-lyrics-web
        image: alkrauss48/cyrus-lyrics-web:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "1m"
          limits:
            memory: "50Mi"
            cpu: "20m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cyrus-lyrics-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cyrus-lyrics-web
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: cyrus-lyrics-web
  namespace: flux-system
spec:
  image: alkrauss48/cyrus-lyrics-web
  interval: 1m0s
