apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mothercodesbest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: laylark/mothercodesbest.dev-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "1m"
          limits:
            memory: "50Mi"
            cpu: "20m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mothercodesbest-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mothercodesbest-frontend
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: mothercodesbest-frontend
  namespace: flux-system
spec:
  image: laylark/mothercodesbest.dev-frontend
  interval: 1m0s
