apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: nicu-calculations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nicu-calculations
        image: laylark/nicu-calculations-app:1.0.2 # {"$imagepolicy": "flux-system:nicu-calculations-app"}
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "50m"
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nicu-calculations-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nicu-calculations-app
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nicu-calculations-app
  namespace: flux-system
spec:
  image: laylark/nicu-calculations-app
  interval: 1m0s
