apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: resume-haus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      initContainers:
        - name: storage-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: storage
              mountPath: /data
      containers:
      - name: app
        image: alkrauss48/resume-haus:latest # {"$imagepolicy": "flux-system:resume-haus-web"}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: "/app/storage"
        env:
        - name: ENVIRONMENT
          value: production
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: app
              key: appId
        - name: CRAFT_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: craftLicenseKey
        - name: SECURITY_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: securityKey
        - name: DB_DRIVER
          value: mysql
        - name: DB_SERVER
          value: db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: DB_SCHEMA
          value: public
        - name: DB_TABLE_PREFIX
          valueFrom:
            secretKeyRef:
              name: app
              key: tablePrefix
        - name: CP_TRIGGER
          value: admin
        - name: PRIMARY_SITE_URL
          value: "https://resumeha.us"
        - name: GMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: app
              key: gmailUsername
        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app
              key: gmailPassword
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: resume-haus-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: resume-haus-web
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: resume-haus-web
  namespace: flux-system
spec:
  image: alkrauss48/resume-haus
  interval: 1m0s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: resume-haus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
      initContainers:
        - name: database-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: database
              mountPath: /data
      containers:
      - name: db
        image: alkrauss48/resume-haus-db:latest # {"$imagepolicy": "flux-system:resume-haus-db"}
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db
                key: rootPassword
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: resume-haus-db
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: resume-haus-db
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: resume-haus-db
  namespace: flux-system
spec:
  image: alkrauss48/resume-haus-db
  interval: 1m0s
