apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: simple-slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: alkrauss48/simple-slides-laravel:1.0.1 # {"$imagepolicy": "flux-system:simple-slides"}
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: Simple Slides
        - name: APP_ENV
          value: production
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: appKey
        - name: APP_DEBUG
          value: "false"
        - name: PHP_CLI_SERVER_WORKERS
          value: "3"
        - name: APP_URL
          value: https://simpleslides.dev
        - name: LOG_LEVEL
          value: critical
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: BROADCAST_DRIVER
          value: redis
        - name: CACHE_DRIVER
          value: redis
        - name: QUEUE_CONNECTION
          value: sync
        - name: SESSION_DRIVER
          value: redis
        - name: FILESYSTEM_DISK
          value: do
        - name: SESSION_LIFETIME
          value: "120"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PASSWORD
          value: "null"
        - name: REDIS_PORT
          value: "6379"
        - name: MAIL_MAILER
          value: smtp
        - name: MAIL_HOST
          value: smtp.sendgrid.net
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_USERNAME
          value: apikey
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app
              key: sendgridApiToken
        - name: MAIL_ENCRYPTION
          value: tls
        - name: MAIL_FROM_NAME
          value: Simple Slides
        - name: MAIL_FROM_ADDRESS
          value: no-reply@simpleslides.dev
        - name: DO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanAccessKey
        - name: DO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanSecretKey
        - name: DO_DEFAULT_REGION
          value: nyc3
        - name: DO_BUCKET
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanBucket
        - name: DO_ENDPOINT
          value: https://nyc3.digitaloceanspaces.com/
        - name: FILAMENT_FILESYSTEM_DISK
          value: do
        - name: MEDIA_DISK
          value: do
        - name: MEDIA_PREFIX
          value: simpleslides.dev/user-uploads
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: simple-slides
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-slides
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: simple-slides
  namespace: flux-system
spec:
  image: alkrauss48/simple-slides-laravel
  interval: 1m0s
