apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: simple-slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: simple-slides
        image: alkrauss48/simple-slides:1.5.4 # {"$imagepolicy": "flux-system:simple-slides"}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "1m"
          limits:
            memory: "50Mi"
            cpu: "20m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: simple-slides
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-slides
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: simple-slides
  namespace: flux-system
spec:
  image: alkrauss48/simple-slides
  interval: 1m0s
