apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: simple-slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: alkrauss48/simple-slides-laravel:1.7.0 # {"$imagepolicy": "flux-system:simple-slides"}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: envs
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: appKey
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app
              key: sendgridApiToken
        - name: DO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanAccessKey
        - name: DO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanSecretKey
        - name: DO_BUCKET
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanBucket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: simple-slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: alkrauss48/simple-slides-laravel:1.7.0 # {"$imagepolicy": "flux-system:simple-slides"}
        command:
        - s6-svscan
        - /etc/s6/worker
        envFrom:
        - configMapRef:
            name: envs
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: appKey
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app
              key: sendgridApiToken
        - name: DO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanAccessKey
        - name: DO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanSecretKey
        - name: DO_BUCKET
          valueFrom:
            secretKeyRef:
              name: app
              key: digitalOceanBucket
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: simple-slides
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-slides
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: simple-slides
  namespace: flux-system
spec:
  image: alkrauss48/simple-slides-laravel
  interval: 1m0s
