apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: takahashi-slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: takahashi-slides
        image: alkrauss48/takahashi-slides:1.0.0 # {"$imagepolicy": "flux-system:takahashi-slides"}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "1m"
          limits:
            memory: "50Mi"
            cpu: "20m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: takahashi-slides
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: takahashi-slides
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: takahashi-slides
  namespace: flux-system
spec:
  image: alkrauss48/takahashi-slides
  interval: 1m0s
