apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: the-krauss-haus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: the-krauss-haus-web
        image: alkrauss48/the-krauss-haus-web:1.17.0 # {"$imagepolicy": "flux-system:the-krauss-haus-web"}
        ports:
        - containerPort: 3000
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: the-krauss-haus-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: the-krauss-haus-web
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: the-krauss-haus-web
  namespace: flux-system
spec:
  image: alkrauss48/the-krauss-haus-web
  interval: 1m0s
