apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: the-krauss-haus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: the-krauss-haus-web
        image: alkrauss48/the-krauss-haus-web:1.25.1 # {"$imagepolicy": "flux-system:the-krauss-haus-web"}
        ports:
        - containerPort: 3000
        env:
        - name: BAR_API_URL
          value: http://app.ask-eddie.svc.cluster.local
        - name: BAR_API_KEY
          valueFrom:
            secretKeyRef:
              name: app
              key: barApiKey
        - name: BAR_CLIENT_RATE_PER_MIN
          value: "8"
        - name: BAR_CONNECT_TIMEOUT_MS
          value: "30000"
        - name: BAR_IDLE_TIMEOUT_MS
          value: "75000"
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: the-krauss-haus-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: the-krauss-haus-web
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: the-krauss-haus-web
  namespace: flux-system
spec:
  image: alkrauss48/the-krauss-haus-web
  interval: 1m0s
