apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: thecodeboss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: alkrauss48/thecodeboss-hugo:1.3.1 # {"$imagepolicy": "flux-system:thecodeboss"}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "1m"
          limits:
            memory: "80Mi"
            cpu: "20m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: thecodeboss
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: thecodeboss
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: thecodeboss
  namespace: flux-system
spec:
  image: alkrauss48/thecodeboss-hugo
  interval: 1m0s
